### PR TITLE
Fixed stupid missing $ bug

### PR DESCRIPTION
**Pull request by franton**
I forgot to add a $ to two lines in my original PR. Adding this allows the building / department code to trigger install policies to work.

### CODE REVIEW

**Comment by loceee** [comment]
hey man! looks good but can't automerge. don't have time to look at this right now.. but soon! back in macadmin land man!

**Comment by franton** [comment]
I just added 10.12 software update compatibility mate.

**Comment by loceee** [comment]
Can I get these changes re-pulled against master? it won't automerge and I am too derp to fix. Thanks!

**Comment by franton** [comment]
I think you're better off doing a copy + paste ;) But yeah, I'll do a PR against master if you're happy it all works.

**Pull request closed without merging**
