### PR TITLE
UUID and CocoaDialog changes

### PR DESCRIPTION
**Pull request by franton**
Hi,

This is old but it works (as far as I can tell). I also made the UUID changes you suggested.

For those who haven't seen this, this commit does the following:

1) removal of osascript calls for menu dialogs and replace with cocoadialog calls.
this is so we can run over the login window.
2) change from using computer mac address to the UUID for casper inventory identification.

### CODE REVIEW

**Comment by franton** [comment]
You've since merged some other changes, so patchoo's version will have to be incrementally changed after any merge.

**Comment by loceee** [comment]
Cool. Only
Thing Id like added to merge this is some code that during check for CDialog, if it's not found it calls a
'jamf policy -trigger $installcdttrigger'

The AppleScript dialogs were in place because Patchoo Deploy could be run on a OOTB Mac perhaps on enrollmentComplete without CDialog installed. It makes sense for Patchoo to look after itself and get it installed. 

I will add this after merge unless you have time to add that.

**Comment by franton** [comment]
I'll add the code. I've got some time to do that tonight.

**Comment by franton** [comment]
Ok that's done. I'll cancel this request and create a new one.

**Pull request closed without merging**
